<?php

namespace QueSoft\Ntak\Enums;

use MyCLabs\Enum\Enum;

final class NTAKAggregateCause extends Enum
{
    const UZEMSZUNET_ARAMSZOLGALTATAS_TERVEZETT_KIMARADASA_MIATT = "UZEMSZUNET_ARAMSZOLGALTATAS_TERVEZETT_KIMARADASA_MIATT";
    const UZEMSZUNET_INTERNETSZOLGALTATAS_TERVEZETT_KIMARADASA_MIATT = "UZEMSZUNET_INTERNETSZOLGALTATAS_TERVEZETT_KIMARADASA_MIATT";
    const UZEMZAVAR_ARAMSZOLGALTATAS_ATMENETI_KIMARADASA_MIATT = "UZEMZAVAR_ARAMSZOLGALTATAS_ATMENETI_KIMARADASA_MIATT";
    const UZEMZAVAR_INTERNETSZOLGALTATAS_ATMENETI_KIMARADASA_MIATT = "UZEMZAVAR_INTERNETSZOLGALTATAS_ATMENETI_KIMARADASA_MIATT";
    const UZEMZAVAR_TERMESZETI_KATASZTROFA_MIATT = "UZEMZAVAR_TERMESZETI_KATASZTROFA_MIATT";
    const UZEMZAVAR_LEJART_TANUSITVANY_MIATT = "UZEMZAVAR_LEJART_TANUSITVANY_MIATT";
    const UZEMZAVAR_MUSZAKI_HIBA_MIATT = "UZEMZAVAR_MUSZAKI_HIBA_MIATT";
}
